### ISSUE TITLE
enable export of converted coordinates

### ISSUE THREAD

**Issue by romunov** [zkuralt/WGStoGK#9]
Add a button which enables user to export the converted data.frame.

**Comment by romunov** [comment]
[This commi](https://github.com/zkuralt/WGStoGK/commit/12c4f640ee45a330688097b84af993a472c96308) introduces file download, but the filename of the downloaded file is wrong. You probably want `filename` instead of `file`?

**Comment by zkuralt** [comment]
There is an encoding issue when downloading csv with original coordinates containing degree sign ( ° ). The issue occurs when downloading from web app on [zkuralt.shinyapps.io/wgstogk](https://zkuralt.shinyapps.io/wgstogk/)

**Comment by zkuralt** [comment]
Encoding of the downloaded file is UTF-8 and the file is displayed correctly in Notepad++. If you want to display it correctly in Excel you should do this through Data > From text and select UTF-8 encoding.
